//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.03 at 09:26:31 PM MST 
//


package org.example.heroschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="general">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="heroName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="male" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="nemisis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="power" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weakness" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sidekick" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="secretIdentity">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="job" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lair" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="secretKeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="costume">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="hair" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="boot" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="skin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="costume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="glove" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="cape" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="underwear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="belt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "general",
    "secretIdentity",
    "costume"
})
@XmlRootElement(name = "hero")
public class Hero {

    @XmlElement(required = true)
    protected Hero.General general;
    @XmlElement(required = true)
    protected Hero.SecretIdentity secretIdentity;
    @XmlElement(required = true)
    protected Hero.Costume costume;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link Hero.General }
     *     
     */
    public Hero.General getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hero.General }
     *     
     */
    public void setGeneral(Hero.General value) {
        this.general = value;
    }

    /**
     * Gets the value of the secretIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link Hero.SecretIdentity }
     *     
     */
    public Hero.SecretIdentity getSecretIdentity() {
        return secretIdentity;
    }

    /**
     * Sets the value of the secretIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hero.SecretIdentity }
     *     
     */
    public void setSecretIdentity(Hero.SecretIdentity value) {
        this.secretIdentity = value;
    }

    /**
     * Gets the value of the costume property.
     * 
     * @return
     *     possible object is
     *     {@link Hero.Costume }
     *     
     */
    public Hero.Costume getCostume() {
        return costume;
    }

    /**
     * Sets the value of the costume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hero.Costume }
     *     
     */
    public void setCostume(Hero.Costume value) {
        this.costume = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="hair" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="boot" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="skin" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="costume" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="glove" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="cape" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="underwear" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="belt" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file",
        "hair",
        "logo",
        "boot",
        "skin",
        "costume",
        "glove",
        "cape",
        "underwear",
        "belt"
    })
    public static class Costume {

        protected int file;
        protected int hair;
        protected int logo;
        protected int boot;
        protected int skin;
        protected int costume;
        protected int glove;
        protected int cape;
        protected int underwear;
        protected int belt;

        /**
         * Gets the value of the file property.
         * 
         */
        public int getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         */
        public void setFile(int value) {
            this.file = value;
        }

        /**
         * Gets the value of the hair property.
         * 
         */
        public int getHair() {
            return hair;
        }

        /**
         * Sets the value of the hair property.
         * 
         */
        public void setHair(int value) {
            this.hair = value;
        }

        /**
         * Gets the value of the logo property.
         * 
         */
        public int getLogo() {
            return logo;
        }

        /**
         * Sets the value of the logo property.
         * 
         */
        public void setLogo(int value) {
            this.logo = value;
        }

        /**
         * Gets the value of the boot property.
         * 
         */
        public int getBoot() {
            return boot;
        }

        /**
         * Sets the value of the boot property.
         * 
         */
        public void setBoot(int value) {
            this.boot = value;
        }

        /**
         * Gets the value of the skin property.
         * 
         */
        public int getSkin() {
            return skin;
        }

        /**
         * Sets the value of the skin property.
         * 
         */
        public void setSkin(int value) {
            this.skin = value;
        }

        /**
         * Gets the value of the costume property.
         * 
         */
        public int getCostume() {
            return costume;
        }

        /**
         * Sets the value of the costume property.
         * 
         */
        public void setCostume(int value) {
            this.costume = value;
        }

        /**
         * Gets the value of the glove property.
         * 
         */
        public int getGlove() {
            return glove;
        }

        /**
         * Sets the value of the glove property.
         * 
         */
        public void setGlove(int value) {
            this.glove = value;
        }

        /**
         * Gets the value of the cape property.
         * 
         */
        public int getCape() {
            return cape;
        }

        /**
         * Sets the value of the cape property.
         * 
         */
        public void setCape(int value) {
            this.cape = value;
        }

        /**
         * Gets the value of the underwear property.
         * 
         */
        public int getUnderwear() {
            return underwear;
        }

        /**
         * Sets the value of the underwear property.
         * 
         */
        public void setUnderwear(int value) {
            this.underwear = value;
        }

        /**
         * Gets the value of the belt property.
         * 
         */
        public int getBelt() {
            return belt;
        }

        /**
         * Sets the value of the belt property.
         * 
         */
        public void setBelt(int value) {
            this.belt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="heroName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="male" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="nemisis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="power" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weakness" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sidekick" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "heroName",
        "male",
        "nemisis",
        "power",
        "weakness",
        "sidekick"
    })
    public static class General {

        @XmlElement(required = true)
        protected String heroName;
        protected boolean male;
        @XmlElement(required = true)
        protected String nemisis;
        @XmlElement(required = true)
        protected String power;
        @XmlElement(required = true)
        protected String weakness;
        protected boolean sidekick;

        /**
         * Gets the value of the heroName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeroName() {
            return heroName;
        }

        /**
         * Sets the value of the heroName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeroName(String value) {
            this.heroName = value;
        }

        /**
         * Gets the value of the male property.
         * 
         */
        public boolean isMale() {
            return male;
        }

        /**
         * Sets the value of the male property.
         * 
         */
        public void setMale(boolean value) {
            this.male = value;
        }

        /**
         * Gets the value of the nemisis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNemisis() {
            return nemisis;
        }

        /**
         * Sets the value of the nemisis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNemisis(String value) {
            this.nemisis = value;
        }

        /**
         * Gets the value of the power property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPower() {
            return power;
        }

        /**
         * Sets the value of the power property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPower(String value) {
            this.power = value;
        }

        /**
         * Gets the value of the weakness property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeakness() {
            return weakness;
        }

        /**
         * Sets the value of the weakness property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeakness(String value) {
            this.weakness = value;
        }

        /**
         * Gets the value of the sidekick property.
         * 
         */
        public boolean isSidekick() {
            return sidekick;
        }

        /**
         * Sets the value of the sidekick property.
         * 
         */
        public void setSidekick(boolean value) {
            this.sidekick = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="job" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lair" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="secretKeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "birthdate",
        "origin",
        "job",
        "lair",
        "secretKeeper"
    })
    public static class SecretIdentity {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String birthdate;
        @XmlElement(required = true)
        protected String origin;
        @XmlElement(required = true)
        protected String job;
        @XmlElement(required = true)
        protected String lair;
        @XmlElement(required = true)
        protected String secretKeeper;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the birthdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthdate() {
            return birthdate;
        }

        /**
         * Sets the value of the birthdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthdate(String value) {
            this.birthdate = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the job property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJob() {
            return job;
        }

        /**
         * Sets the value of the job property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJob(String value) {
            this.job = value;
        }

        /**
         * Gets the value of the lair property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLair() {
            return lair;
        }

        /**
         * Sets the value of the lair property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLair(String value) {
            this.lair = value;
        }

        /**
         * Gets the value of the secretKeeper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecretKeeper() {
            return secretKeeper;
        }

        /**
         * Sets the value of the secretKeeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecretKeeper(String value) {
            this.secretKeeper = value;
        }

    }

}
