//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 01:59:39 PM MST 
//


package com.grillrite.parts;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="part" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="partName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cost" type="{http://grillrite.com/datatypes}priceType"/>
 *                   &lt;element name="inStock" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="partID" type="{http://grillrite.com/datatypes}itemID" />
 *                 &lt;attribute name="usedIn" type="{http://grillrite.com/datatypes}itemIDREFS" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "part"
})
@XmlRootElement(name = "grillParts")
public class GrillParts {

    @XmlElement(required = true)
    protected List<GrillParts.Part> part;

    /**
     * Gets the value of the part property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the part property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrillParts.Part }
     * 
     * 
     */
    public List<GrillParts.Part> getPart() {
        if (part == null) {
            part = new ArrayList<GrillParts.Part>();
        }
        return this.part;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="partName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cost" type="{http://grillrite.com/datatypes}priceType"/>
     *         &lt;element name="inStock" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       &lt;/sequence>
     *       &lt;attribute name="partID" type="{http://grillrite.com/datatypes}itemID" />
     *       &lt;attribute name="usedIn" type="{http://grillrite.com/datatypes}itemIDREFS" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partName",
        "cost",
        "inStock"
    })
    public static class Part {

        @XmlElement(required = true)
        protected String partName;
        @XmlElement(required = true)
        protected String cost;
        @XmlElement(required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger inStock;
        @XmlAttribute(name = "partID")
        protected String partID;
        @XmlAttribute(name = "usedIn")
        protected List<String> usedIn;

        /**
         * Gets the value of the partName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartName() {
            return partName;
        }

        /**
         * Sets the value of the partName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartName(String value) {
            this.partName = value;
        }

        /**
         * Gets the value of the cost property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCost() {
            return cost;
        }

        /**
         * Sets the value of the cost property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCost(String value) {
            this.cost = value;
        }

        /**
         * Gets the value of the inStock property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getInStock() {
            return inStock;
        }

        /**
         * Sets the value of the inStock property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setInStock(BigInteger value) {
            this.inStock = value;
        }

        /**
         * Gets the value of the partID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartID() {
            return partID;
        }

        /**
         * Sets the value of the partID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartID(String value) {
            this.partID = value;
        }

        /**
         * Gets the value of the usedIn property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the usedIn property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsedIn().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getUsedIn() {
            if (usedIn == null) {
                usedIn = new ArrayList<String>();
            }
            return this.usedIn;
        }

    }

}
