CREATE TABLE INVENTORY(inv_id NUMBER(3), item_id NUMBER(3), color VARCHAR2(20), inv_size VARCHAR2(3), inv_price NUMBER(8,2) NOT NULL, inv_qoh NUMBER(4) NOT NULL, CONSTRAINT pk_inv_id PRIMARY KEY(inv_id), CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES ITEM(item_id));


CREATE TABLE ORDERS(o_id NUMBER(2), o_date DATE NOT NULL, o_methpmt VARCHAR2(20), c_id NUMBER(2) NOT NULL, os_id NUMBER(2) NOT NULL, CONSTRAINT pk_o_id PRIMARY KEY(o_id), CONSTRAINT fk_c_id FOREIGN KEY (c_id) REFERENCES CUSTOMER(c_id), CONSTRAINT fk_os_id FOREIGN KEY(os_id) REFERENCES ORDER_SOURCE(os_id));


CREATE TABLE CUSTOMER(c_id NUMBER(3), c_last VARCHAR2(20) NOT NULL, c_first VARCHAR2(20) NOT NULL, c_mi VARCHAR2(1), c_dob DATE NOT NULL, c_address VARCHAR2(30) NOT NULL, c_city VARCHAR2(20) NOT NULL, c_state VARCHAR2(2) NOT NULL, c_zip NUMBER(5) NOT NULL , c_dphone VARCHAR2(10) NOT NULL, c_ephone VARCHAR2(10) NOT NULL, c_user_id VARCHAR2(20) NOT NULL UNIQUE, c_password VARCHAR2(20) NOT NULL, CONSTRAINT pk_c_id PRIMARY KEY(c_id));


CREATE TABLE ORDER_SOURCE(os_id NUMBER(2) NOT NULL, os_desc VARCHAR2(100) NOT NULL UNIQUE, CONSTRAINT pk_os_id PRIMARY KEY(os_id));


CREATE TABLE ITEM(item_id NUMBER(2), item_desc VARCHAR2(100) NOT NULL UNIQUE, cat_id NUMBER(1), item_image VARCHAR2(20) NOT NULL UNIQUE, CONSTRAINT pk_item_id PRIMARY KEY (item_id),CONSTRAINT fk_cat_id  FOREIGN KEY (cat_id) REFERENCES CATEGORY(cat_id));


CREATE TABLE CATEGORY(cat_id NUMBER(1), cat_desc VARCHAR2(100) NOT NULL UNIQUE, CONSTRAINT pk_cat_id PRIMARY KEY(cat_id));

RENAME ORDERS TO 'ORDER';
ALTER TABLE CUSTOMER DROP COLUMN C_MI;
ALTER 'ORDER' MODIFY(O_METHPMT CHAR(20));
SELECT * FROM user_constraints WHERE table_name = 'ORDER';
DROP TABLE ORDER_SOURCE;